# Generated by Django 6.0.4 on 2026-05-03 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecilenHedef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hedef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.hedef')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seçilen Hedef',
                'verbose_name_plural': 'Seçilen Hedefler',
            },
        ),
        migrations.CreateModel(
            name='HedefNot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_metni', models.TextField()),
                ('duygu_skoru', models.FloatField(blank=True, null=True)),
                ('ai_motivasyon_notu', models.TextField(blank=True, null=True)),
                ('secilen_hedef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.secilenhedef')),
            ],
            options={
                'verbose_name': 'Hedef Notu',
                'verbose_name_plural': 'Hedef Notları',
            },
        ),
    ]
