# Generated by Django 6.0.4 on 2026-05-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hedef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('ikon', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
            ],
            options={
                'verbose_name': 'Hedef',
                'verbose_name_plural': 'Hedefler',
            },
        ),
    ]
