# Generated by Django 6.0.4 on 2026-05-08 21:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_hedefnot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hedefnot',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
